### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by MatthewBarroso**

### CODE REVIEW

**Comment by ChujieChen** [comment]
please resolve conflicts

**Review by ChujieChen — COMMENTED** [review]
I see a lot of changes in `client/package-lock.json`

Are you using some extra packages? or a different node version?

**Comment by MatthewBarroso** [comment]
Hm I'm not sure. I didn't mean to make any changes there, is there a way I can fix this?

**Review by ChujieChen — APPROVED** [review]
lgtm

**Pull request merged**
